-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 17:58:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xDev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xDev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xDev` DEFAULT CHARACTER SET utf8 ;
USE `xDev` ;

-- -----------------------------------------------------
-- Table `xDev`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`produtos` (
  `idprodutos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`idprodutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xDev`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `hora` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`idpedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xDev`.`produtos_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xDev`.`produtos_pedidos` (
  `idprodutos_pedidos` INT NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(100) NULL,
  `produtos_idprodutos` INT NOT NULL,
  `pedidos_idpedidos` INT NOT NULL,
  PRIMARY KEY (`idprodutos_pedidos`),
  INDEX `fk_produtos_pedidos_produtos_idx` (`produtos_idprodutos` ASC),
  INDEX `fk_produtos_pedidos_pedidos1_idx` (`pedidos_idpedidos` ASC),
  CONSTRAINT `fk_produtos_pedidos_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `xDev`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pedidos_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `xDev`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO produtos VALUES (DEFAULT,"X salada simples",2.00);
INSERT INTO produtos VALUES (DEFAULT,"X salada completo",5.00);
INSERT INTO produtos VALUES (DEFAULT,"X simples",1.50);
INSERT INTO produtos VALUES (DEFAULT,"X coração",9.00);
INSERT INTO produtos VALUES (DEFAULT,"X egg",9.20);
INSERT INTO produtos VALUES (DEFAULT,"Coca-cola lata",3.00);
INSERT INTO produtos VALUES (DEFAULT,"Coca-cola 2 litros",8.00);
INSERT INTO produtos VALUES (DEFAULT,"soda lata",3.00);
INSERT INTO produtos VALUES (DEFAULT,"sprite lata",3.00);
INSERT INTO produtos VALUES (DEFAULT,"suco",3.50);


INSERT INTO pedidos VALUES(DEFAULT, CURRENT_TIME(), 0);
INSERT INTO pedidos VALUES(DEFAULT, CURRENT_TIME(), 0);
INSERT INTO pedidos VALUES(DEFAULT, CURRENT_TIME(), 0);
INSERT INTO pedidos VALUES(DEFAULT, CURRENT_TIME(), 0);

INSERT INTO produtos_pedidos VALUES(DEFAULT,'sem alface e ervilha e entregar na casa da esquina',4,1)